# This configures the Continuous Integration builds on every PR
name: CI

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      
      - name: Install deb packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            python3-pip \
            clang-format

      - name: Install Cython
        run: |
          python3 -m pip install Cython

      - name: Install protobuf
        run: |
          wget https://github.com/protocolbuffers/protobuf/releases/download/v3.15.1/protobuf-cpp-3.15.1.tar.gz
          tar -xzf protobuf-cpp-3.15.1.tar.gz
          cd protobuf-3.15.1 && ./configure && make && sudo make install && sudo ldconfig

      - name: Install protobuf-c
        run: |
          wget https://github.com/protobuf-c/protobuf-c/releases/download/v1.3.3/protobuf-c-1.3.3.tar.gz
          tar -xzf protobuf-c-1.3.3.tar.gz
          cd protobuf-c-1.3.3 && ./configure && make && sudo make install && sudo ldconfig
      
      - name: Build
        run: |
          ./runtime build
      
      - name: Test
        run: |
          ./runtime test int
